# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p9VG6786XLtWv9szf-owFmwAMxucKhEP
"""

age=31
print("age is:", age)

ch={1,2,8,8,9,7,6}
print("printing",ch)

Employee={"name": "Rabah", "age":31, "CGPA" :2.79}
print(Employee)
print(["age"])

from enum import unique
nums={1,3,3,8,9,8,6,2,4,4,5}
unique=set(nums)
print(unique)

s="hello"
result=list(dict.fromkeys(s))
print(result)

fruits = ["Apple","Banana","mango","grapes"]

for index, fruit in enumerate(fruits):
    print(index, fruit)

#variables for data types
name=str(input("enter your name:"))
age=int(input("enter your age:"))

print("hello",name ,"you are",age ,"years old")

#simple calculator using arithmethic oprations
num1=int(input("enter your 1st number:"))
num2=int (input("enter your 2nd number:"))

add=num1+num2
print(add)

diffrence=num1-num2
print(diffrence)

product=num1*num2
print(product)

division=num1/num2
print(division)

#working with list
fruits=["apple","banana","grapes","mango"]
print("first fruit",[0])
print("last fruit",[-1])
print("Lenght of fruits",len(fruits))

#Simple Function
def add(a,b):
 return a + b

result=add(5,8)
print(result)

word=["netsol","is","netsol"]

for word in word:

 print(word)

letter="netsol"
for letter in word:
  print(letter)

word="netsolpark"

for letter in word:
  if letter =="n" or letter =="s":
   continue
  print(letter)

words="netsolpark"
for letter in words:
 if letter == "e" or letter =="s":
   break
   print(letter)

for i in range(2):
  for j in range(1,4):
    print(j, end="     ")
  print()

num = int(input("Enter a number"))
if num % 2==0:
  print("number is even")
else:
  print("Number is odd")

firstname=str(input("Enter your first name : "))
Lastname=str(input("Enter your last name : "))

print(firstname,Lastname)

def cube_number():
 num=float(input("enter a number"))
 return num ** 3

result=cube_number()
print("cube number is:", result)

20+35+4+27

86/4

import numpy as np
import random
import pandas as pd

heads = 0
tails = 0

for i in range(1000):
  coin = random.choice(["H" , "T"])

  if coin=="H":
    heads += 1

  else:
     tails +=1

print("Heads" , heads)
print("Tails" , tails)

print ("", heads/1000)
print ("" , tails/1000)

import numpy as np
from statistics import mode

data =[10,20,30,40,50,60,70]

print("mean " , np.mean(data))
print("meadian" , np.median(data))
print("mode" , mode(data))
print("SD" , np.std(data))

import matplotlib.pyplot as plt

P_disease = 0.1
P_positive_disease = 0.95
P_positive = 0.05


P_positive_given_disease = (P_positive_disease * P_disease) / P_positive
print(P_positive_given_disease)

values = [P_positive_given_disease, 1 - P_positive_given_disease]
labels = ["Disease Given Positive", "No Disease"]


plt.pie(values, labels=labels, autopct='%1.1f%%')
plt.title("Probability Distribution")
plt.show()

import matplotlib.pyplot as plt

P_disease = 0.1
P_positive_disease = 0.95
P_positive= 0.05
P_positive_given_disease = (P_positive_disease * P_disease)/P_positive
print(P_positive_given_disease)

import numpy as np

sample_population = [172,125,160,180,190,145,155]
sample_mean = np.mean (sample_population)
print("estimated average" , sample_mean)

import numpy as np
import matplotlib.pyplot as plt

sample_population = [172,125,160,180,190,145,155]


sample_mean = np.mean(sample_population)
print("Estimated average:", sample_mean)


x = [1,2,3,4,5,6,7]


plt.plot(x, sample_population)


plt.xlabel("Sample Number")
plt.ylabel("Height Values")
plt.title("Sample Population Line Graph")


plt.show()

import sklearn
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
import pandas as pd
import matplotlib.pyplot as plt

df = pd.DataFrame(load_diabetes().data)
diabetes= load_diabetes()

X = diabetes.data
y= diabetes.target

# Split data into training and testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

# Train model
model = KNeighborsClassifier(n_neighbors=5)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)


accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

labels = ["Accuracy"]
values = [accuracy]

plt.bar(labels, values)
plt.title("Bar chart")
plt.ylabel("accuracy")

plt.show

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

# Load dataset
diabetes = load_diabetes()

X = diabetes.data
y = diabetes.target

# Convert regression target into classification
y = (y > np.mean(y)).astype(int)

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.90)

# Train model
model = KNeighborsClassifier(n_neighbors=2)
model.fit(X_train, y_train)

# Predict
y_pred = model.predict(X_test)

# Accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Bar chart
labels = ["Accuracy"]
values = [accuracy]

plt.bar(labels, values, color="red")
plt.title("Model Accuracy")
plt.ylabel("Accuracy Score")
plt.show()

